BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[TB_PAR_USUARIO] (
    [id] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [TB_PAR_USUARIO_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    [usuario] NVARCHAR(1000) NOT NULL,
    [hash] NVARCHAR(1000) NOT NULL,
    [hashedRt] NVARCHAR(1000),
    [email] NVARCHAR(1000) NOT NULL,
    [nome] NVARCHAR(1000) NOT NULL,
    [codPessoa] INT,
    [codigo_recuperacao] NVARCHAR(1000),
    [ultimoLogin] DATETIME2,
    CONSTRAINT [TB_PAR_USUARIO_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [TB_PAR_USUARIO_usuario_key] UNIQUE NONCLUSTERED ([usuario])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
